/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.BookDAO;
import DAO.IssueBookDAO;
import DAO.MemberDAO;
import My_Functions.Func_Class;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Manh Hai
 */
public class IssueBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    
    DAO.MemberDAO member = new MemberDAO();
    
    My_Functions.Func_Class func = new Func_Class();
    
    DAO.BookDAO book = new BookDAO();
    
    DAO.IssueBookDAO issue_Book = new IssueBookDAO();
    
    boolean book_exist = false;
    boolean member_exist = false;
    
    private int Book_id_search;
    private int Member_id_search;
    
    public IssueBookForm() {
        initComponents();
        
        // set center the form 
        this.setLocationRelativeTo(null);
        
        // add a border to the panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108,122,137));
        jPanel1.setBorder(panelHeaderBorder);
        
        // display image in the top
        func.displayImageByPath(90, 60, "../My_Images/organizer.png", jLabel_FormTitle);

        setBorderToJlabel(jLabel_BookName_, Color.white);
        setBorderToJlabel(jLabel_MemberFullname_, Color.white);
        
        jLabel_BookName_.setVisible(false);
        jLabel_MemberFullname_.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel_CloseForm_ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_BookID_ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_IssueBook_ = new javax.swing.JButton();
        jButton_Cancel_ = new javax.swing.JButton();
        jDateChooser_ReturnDate_ = new com.toedter.calendar.JDateChooser();
        jButton_Search_Book_ = new javax.swing.JButton();
        jLabel_Avaliable_ = new javax.swing.JLabel();
        jTextField_MemberID_ = new javax.swing.JTextField();
        jButton_Search_Member_ = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser_IssueDate_ = new com.toedter.calendar.JDateChooser();
        jLabel_BookName_ = new javax.swing.JLabel();
        jLabel_MemberFullname_ = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note_ = new javax.swing.JTextArea();

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Book Desciption:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_FormTitle.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_FormTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Issue Book");
        jLabel_FormTitle.setOpaque(true);

        jLabel_CloseForm_.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm_.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_CloseForm_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_.setText("X");
        jLabel_CloseForm_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_.setOpaque(true);
        jLabel_CloseForm_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseForm_MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Enter Book ID:");

        jTextField_BookID_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Note:");

        jButton_IssueBook_.setBackground(new java.awt.Color(204, 255, 204));
        jButton_IssueBook_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_IssueBook_.setText("Issue");
        jButton_IssueBook_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_IssueBook_MouseClicked(evt);
            }
        });
        jButton_IssueBook_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IssueBook_ActionPerformed(evt);
            }
        });

        jButton_Cancel_.setBackground(new java.awt.Color(255, 204, 204));
        jButton_Cancel_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Cancel_.setText("Cancel");
        jButton_Cancel_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Cancel_MouseClicked(evt);
            }
        });
        jButton_Cancel_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancel_ActionPerformed(evt);
            }
        });

        jDateChooser_ReturnDate_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButton_Search_Book_.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton_Search_Book_.setText("Search book");
        jButton_Search_Book_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Search_Book_ActionPerformed(evt);
            }
        });

        jLabel_Avaliable_.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_Avaliable_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_Avaliable_.setText("Yes-or-No");

        jTextField_MemberID_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButton_Search_Member_.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton_Search_Member_.setText("Search member");
        jButton_Search_Member_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Search_Member_ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("Enter Member ID:");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setText("Is this book avaliable: ");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Issue date:");

        jDateChooser_IssueDate_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel_BookName_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_BookName_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_BookName_.setText("Book Name");
        jLabel_BookName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_BookName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseExited(evt);
            }
        });

        jLabel_MemberFullname_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_MemberFullname_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_MemberFullname_.setText("Member Full-name");
        jLabel_MemberFullname_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MemberFullname_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullname_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullname_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullname_MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Return date:");

        jTextArea_Note_.setColumns(20);
        jTextArea_Note_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea_Note_.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note_);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Avaliable_))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jButton_Cancel_, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton_IssueBook_, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(44, 44, 44)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_BookName_)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextField_BookID_, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(jButton_Search_Book_, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_MemberFullname_)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextField_MemberID_, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_Search_Member_, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser_IssueDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(85, 85, 85)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser_ReturnDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_BookID_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search_Book_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BookName_)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_MemberID_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search_Member_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_MemberFullname_)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Avaliable_)
                    .addComponent(jLabel15))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jDateChooser_IssueDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser_ReturnDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel_)
                    .addComponent(jButton_IssueBook_))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IssueBook_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IssueBook_ActionPerformed

        String note = jTextArea_Note_.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            int bookID = Integer.parseInt(jTextField_BookID_.getText());
            int memberID = Integer.parseInt(jTextField_MemberID_.getText());
            String issue_date = dateFormat.format(jDateChooser_IssueDate_.getDate());
            String return_date = dateFormat.format(jDateChooser_ReturnDate_.getDate());
            
            Date issueDate = dateFormat.parse(issue_date);
            Date returnDate = dateFormat.parse(return_date);
            
            if(!book_exist) {
                JOptionPane.showMessageDialog(null, "You need to check if this book exist first when you click the search book button", "Notification", 2);
            } else if(!member_exist) {
                JOptionPane.showMessageDialog(null, "You need to check if this member exist first when you click the search member button", "Notification", 2);
            } else if(!issue_Book.checkBookAvailability(bookID)) {
                JOptionPane.showMessageDialog(null, "This book is not available right now", "Notification", 2);
            } else if(returnDate.before(issueDate)) {
                JOptionPane.showMessageDialog(null, "The Return date must be after Then Issue date", "Notification", 2);
            } else {
                issue_Book.addIssue(bookID, memberID, "issued", issue_date, return_date, note);
                
                // reset fields
                jTextField_BookID_.setText("");
                jTextField_MemberID_.setText("");
                jLabel_BookName_.setText("Book Name");
                jLabel_MemberFullname_.setText("Member Full-name");
                jLabel_Avaliable_.setText("Yes-or-No");
                jLabel_Avaliable_.setForeground(new Color(51,102,255));
                jDateChooser_IssueDate_.setDate(null);
                jDateChooser_ReturnDate_.setDate(null);
                book_exist = false;
                member_exist = false;
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fill in all information", "Notification", 2);
        }
    }//GEN-LAST:event_jButton_IssueBook_ActionPerformed

    private void jButton_IssueBook_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IssueBook_MouseClicked

    }//GEN-LAST:event_jButton_IssueBook_MouseClicked

    private void jLabel_CloseForm_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseForm_MouseClicked
        // close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseForm_MouseClicked

    private void jButton_Search_Book_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_Book_ActionPerformed
        
        if(jTextField_BookID_.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Book ID is Empty", "Notification", 2);
        } else {
            int book_id = Integer.parseInt(jTextField_BookID_.getText());
            try {
                DTO.BookDTO selected_book = book.getBookByID(book_id);
                if(selected_book != null) {
                    jLabel_BookName_.setVisible(true);
                    jLabel_BookName_.setText(selected_book.getName());
                    book_exist = true;
                    Book_id_search = book_id;
                    
                    // display availability
                    if(issue_Book.checkBookAvailability(book_id)) {
                        jLabel_Avaliable_.setText("YES");
                        jLabel_Avaliable_.setForeground(Color.green);
                    } else {
                        jLabel_Avaliable_.setText("NO");
                        jLabel_Avaliable_.setForeground(Color.red);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "This book doesn't exist", "Notification", 2);
                    book_exist = false;
                    jLabel_Avaliable_.setText("Yes-or-No");
                    jLabel_Avaliable_.setForeground(new Color(51,51,255));
                    jLabel_BookName_.setText("Book Name");
                    jLabel_BookName_.setVisible(false);
                }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_Search_Book_ActionPerformed

    private void jButton_Cancel_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancel_ActionPerformed
        // close this window
        this.dispose();
    }//GEN-LAST:event_jButton_Cancel_ActionPerformed

    private void jButton_Cancel_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Cancel_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Cancel_MouseClicked

    private void jButton_Search_Member_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_Member_ActionPerformed
        if(jTextField_MemberID_.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Member ID is Empty", "Notification", 2);
        } else {
            int member_id = Integer.parseInt(jTextField_MemberID_.getText());
            try {
                DTO.MemberDTO selected_member = member.getMemberByID(member_id);
                if(selected_member != null) {
                    String fullname = selected_member.getFirstName() + " " + selected_member.getLastName();
                    jLabel_MemberFullname_.setText(fullname);
                    member_exist = true;
                    Member_id_search = member_id;
                    jLabel_MemberFullname_.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "This member doesn't exist", "Notification", 2);
                    member_exist = false;
                    jLabel_MemberFullname_.setText("Member Full-name");
                    jLabel_MemberFullname_.setVisible(false);
                }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_Search_Member_ActionPerformed

    private void jLabel_BookName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseClicked
        // display the book infomation card
        if(jTextField_BookID_.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Book ID", "Notification", 2);
        } else {
            BookInfoCardForm bicf = new BookInfoCardForm();
            bicf.displayBookInfo(Book_id_search);
            bicf.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_BookName_MouseClicked

    private void jLabel_MemberFullname_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullname_MouseClicked
        // display the member infomation card
        if(jTextField_MemberID_.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Member ID", "Notification", 2);
        } else {
            MemberInfoCardForm micf = new MemberInfoCardForm();
            micf.displayMemberInfo(Member_id_search);
            micf.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_MemberFullname_MouseClicked

    private void jLabel_BookName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseEntered
        // add a border in the bottom of the book name jlabel
        setBorderToJlabel(jLabel_BookName_, new Color(51,102,255));
    }//GEN-LAST:event_jLabel_BookName_MouseEntered

    private void jLabel_BookName_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseExited
        // add a border in the bottom of the book name jlabel
        setBorderToJlabel(jLabel_BookName_, Color.white);
    }//GEN-LAST:event_jLabel_BookName_MouseExited

    private void jLabel_MemberFullname_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullname_MouseEntered
        // add a border in the bottom of the member fullname jlabel
        setBorderToJlabel(jLabel_MemberFullname_, new Color(51,102,255));
    }//GEN-LAST:event_jLabel_MemberFullname_MouseEntered

    private void jLabel_MemberFullname_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullname_MouseExited
        // add a border in the bottom of the member fullname jlabel
        setBorderToJlabel(jLabel_MemberFullname_, Color.white);
    }//GEN-LAST:event_jLabel_MemberFullname_MouseExited

    // create a function to set border
    public void setBorderToJlabel(JLabel label, Color color) {
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, color);
        label.setBorder(border);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel_;
    private javax.swing.JButton jButton_IssueBook_;
    private javax.swing.JButton jButton_Search_Book_;
    private javax.swing.JButton jButton_Search_Member_;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate_;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate_;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Avaliable_;
    private javax.swing.JLabel jLabel_BookName_;
    private javax.swing.JLabel jLabel_CloseForm_;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_MemberFullname_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Note_;
    private javax.swing.JTextField jTextField_BookID_;
    private javax.swing.JTextField jTextField_MemberID_;
    // End of variables declaration//GEN-END:variables
}
