/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Forms;

import My_Classes.Book;
import My_Classes.Func_Class;
import My_Classes.Issue_Book;
import My_Classes.Member;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manh Hai
 */
public class ReturnBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    
    My_Classes.Member member = new Member();
    
    My_Classes.Func_Class func = new Func_Class();
    
    My_Classes.Book book = new Book();
    
    My_Classes.Issue_Book issue_Book = new Issue_Book();
    
    boolean book_exist = false;
    boolean member_exist = false;
    
    private int Book_id_search;
    private int Member_id_search;
    
    public ReturnBookForm() {
        initComponents();
        
        // set center the form 
        this.setLocationRelativeTo(null);
        
        // add a border to the panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108,122,137));
        jPanel1.setBorder(panelHeaderBorder);
        
        // display image in the top
        func.displayImageByPath(90, 60, "../My_Images/organizer.png", jLabel_FormTitle);

        setBorderToJlabel(jLabel_BookName_, Color.white);
        setBorderToJlabel(jLabel_MemberFullname_, Color.white);
        
        jLabel_BookName_.setVisible(false);
        jLabel_MemberFullname_.setVisible(false);
        
        // customize the jtable
        func.customTable(jTable_Issued_Books_);
        
        // cumtomize table header row
        func.customTableHeader(jTable_Issued_Books_, new Color(34, 167, 240), 13);
        
        // populate jtable with issued books
        populateJtableWithIssuedBooks("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel_CloseForm_ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_BookID_ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_Return_ = new javax.swing.JButton();
        jButton_Lost_ = new javax.swing.JButton();
        jDateChooser_ReturnDate_ = new com.toedter.calendar.JDateChooser();
        jTextField_MemberID_ = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser_IssueDate_ = new com.toedter.calendar.JDateChooser();
        jLabel_BookName_ = new javax.swing.JLabel();
        jLabel_MemberFullname_ = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note_ = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Issued_Books_ = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Status_ = new javax.swing.JComboBox<>();
        jButton_Delete_ = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Book Desciption:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_FormTitle.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_FormTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Return Book");
        jLabel_FormTitle.setOpaque(true);

        jLabel_CloseForm_.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm_.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_CloseForm_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_.setText("X");
        jLabel_CloseForm_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_.setOpaque(true);
        jLabel_CloseForm_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseForm_MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Enter Book ID:");

        jTextField_BookID_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_BookID_.setDoubleBuffered(true);
        jTextField_BookID_.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Note:");

        jButton_Return_.setBackground(new java.awt.Color(204, 255, 204));
        jButton_Return_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Return_.setText("Return");
        jButton_Return_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Return_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Return_MouseEntered(evt);
            }
        });
        jButton_Return_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Return_ActionPerformed(evt);
            }
        });

        jButton_Lost_.setBackground(new java.awt.Color(255, 255, 153));
        jButton_Lost_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Lost_.setText("Lost");
        jButton_Lost_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Lost_MouseClicked(evt);
            }
        });
        jButton_Lost_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lost_ActionPerformed(evt);
            }
        });

        jDateChooser_ReturnDate_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextField_MemberID_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_MemberID_.setDoubleBuffered(true);
        jTextField_MemberID_.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("Enter Member ID:");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Issue date:");

        jDateChooser_IssueDate_.setEnabled(false);
        jDateChooser_IssueDate_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel_BookName_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_BookName_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_BookName_.setText("Book Name");
        jLabel_BookName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_BookName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseExited(evt);
            }
        });

        jLabel_MemberFullname_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_MemberFullname_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_MemberFullname_.setText("Member Full-name");
        jLabel_MemberFullname_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MemberFullname_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullname_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullname_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullname_MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Return date:");

        jTextArea_Note_.setColumns(20);
        jTextArea_Note_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea_Note_.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note_);

        jTable_Issued_Books_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable_Issued_Books_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Issued_Books_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Issued_Books_MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Issued_Books_);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Select book status:");

        jComboBox_Status_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox_Status_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "Returned", "Lost" }));
        jComboBox_Status_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Status_ActionPerformed(evt);
            }
        });

        jButton_Delete_.setBackground(new java.awt.Color(255, 204, 204));
        jButton_Delete_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Delete_.setText("Delete");
        jButton_Delete_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Delete_MouseClicked(evt);
            }
        });
        jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_BookName_)
                            .addComponent(jTextField_BookID_, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_MemberFullname_)
                            .addComponent(jTextField_MemberID_, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser_IssueDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(85, 85, 85)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_ReturnDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Lost_, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton_Return_, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_Status_, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_BookID_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_Status_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_BookName_)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_MemberID_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MemberFullname_)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jDateChooser_IssueDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser_ReturnDate_, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Lost_)
                            .addComponent(jButton_Return_)
                            .addComponent(jButton_Delete_)))
                    .addComponent(jScrollPane2))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Return_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Return_ActionPerformed
        
        // return the book
        // we will update the return date
        // the note
        // and the status to returned
        
        String note = jTextArea_Note_.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            int bookID = Integer.parseInt(jTextField_BookID_.getText());
            int memberID = Integer.parseInt(jTextField_MemberID_.getText());
            
            String return_date = dateFormat.format(jDateChooser_ReturnDate_.getDate());
            Date returnDate = dateFormat.parse(return_date);
            
            String issue_date = dateFormat.format(jDateChooser_IssueDate_.getDate());
            Date issueDate = dateFormat.parse(issue_date);
            
            if(returnDate.before(issueDate)) {
                JOptionPane.showMessageDialog(null, "The Return date must be after Then Issue date", "Notification", 2);
            } else {
                issue_Book.updateIssue(bookID, memberID, "returned", issue_date, return_date, note);
                
                // reset fields
                jTextField_BookID_.setText("");
                jTextField_MemberID_.setText("");
                jLabel_BookName_.setText("Book Name");
                jLabel_BookName_.setVisible(false);
                jLabel_MemberFullname_.setText("Member Full-name");
                jLabel_MemberFullname_.setVisible(false);
                jDateChooser_IssueDate_.setDate(null);
                jDateChooser_ReturnDate_.setDate(new Date());
                jTextArea_Note_.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Select book which want to return from table", "Notification", 2);
        }
    }//GEN-LAST:event_jButton_Return_ActionPerformed

    private void jButton_Return_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Return_MouseClicked

    }//GEN-LAST:event_jButton_Return_MouseClicked

    private void jLabel_CloseForm_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseForm_MouseClicked
        // close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseForm_MouseClicked

    private void jButton_Lost_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lost_ActionPerformed
        // the book is lost
        // we need to update the book status to lost
        // and update the book quantity
        // even if the book is lost we will not change the return date
        
        String note = jTextArea_Note_.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            int bookID = Integer.parseInt(jTextField_BookID_.getText());
            int memberID = Integer.parseInt(jTextField_MemberID_.getText());
            
            String return_date = dateFormat.format(jDateChooser_ReturnDate_.getDate());
            Date returnDate = dateFormat.parse(return_date);
            
            String issue_date = dateFormat.format(jDateChooser_IssueDate_.getDate());
            Date issueDate = dateFormat.parse(issue_date);
            
            if(returnDate.before(issueDate)) {
                JOptionPane.showMessageDialog(null, "The Return date must be after Then Issue date", "Notification", 2);
            } else {
                issue_Book.updateIssue(bookID, memberID, "lost", issue_date, return_date, note);
                
                // update the book quantity
                int quantity = new My_Classes.Book().getBookByID(bookID).getQuantity();
                book.setQuantity_Minus_One(bookID, quantity - 1);
                
                // reset fields
                jTextField_BookID_.setText("");
                jTextField_MemberID_.setText("");
                jLabel_BookName_.setText("Book Name");
                jLabel_BookName_.setVisible(false);
                jLabel_MemberFullname_.setText("Member Full-name");
                jLabel_MemberFullname_.setVisible(false);
                jDateChooser_IssueDate_.setDate(null);
                jDateChooser_ReturnDate_.setDate(new Date());
                jTextArea_Note_.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Select book which was lost from table", "Notification", 2);
        }
        
    }//GEN-LAST:event_jButton_Lost_ActionPerformed

    private void jButton_Lost_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Lost_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Lost_MouseClicked

    private void jLabel_BookName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseClicked
        // display the book infomation card
        if(jTextField_BookID_.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Book ID", "Notification", 2);
        } else {
            BookInfoCardForm bicf = new BookInfoCardForm();
            bicf.displayBookInfo(Book_id_search);
            bicf.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_BookName_MouseClicked

    private void jLabel_MemberFullname_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullname_MouseClicked
        // display the member infomation card
        if(jTextField_MemberID_.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Member ID", "Notification", 2);
        } else {
            MemberInfoCardForm micf = new MemberInfoCardForm();
            micf.displayMemberInfo(Member_id_search);
            micf.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_MemberFullname_MouseClicked

    private void jLabel_BookName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseEntered
        // add a border in the bottom of the book name jlabel
        setBorderToJlabel(jLabel_BookName_, new Color(51,102,255));
    }//GEN-LAST:event_jLabel_BookName_MouseEntered

    private void jLabel_BookName_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseExited
        // add a border in the bottom of the book name jlabel
        setBorderToJlabel(jLabel_BookName_, Color.white);
    }//GEN-LAST:event_jLabel_BookName_MouseExited

    private void jLabel_MemberFullname_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullname_MouseEntered
        // add a border in the bottom of the member fullname jlabel
        setBorderToJlabel(jLabel_MemberFullname_, new Color(51,102,255));
    }//GEN-LAST:event_jLabel_MemberFullname_MouseEntered

    private void jLabel_MemberFullname_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullname_MouseExited
        // add a border in the bottom of the member fullname jlabel
        setBorderToJlabel(jLabel_MemberFullname_, Color.white);
    }//GEN-LAST:event_jLabel_MemberFullname_MouseExited

    private void jTable_Issued_Books_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Issued_Books_MouseClicked
        // display the selected issued book
        // get the selected row data
        int index = jTable_Issued_Books_.getSelectedRow();

        // get values
        int book_id = Integer.parseInt(jTable_Issued_Books_.getValueAt(index, 0).toString());
        int member_id = Integer.parseInt(jTable_Issued_Books_.getValueAt(index, 1).toString());
        My_Classes.Book selectedBook;
        My_Classes.Member selectedMember;
        try {
            selectedBook = book.getBookByID(book_id);
            jTextField_BookID_.setText(String.valueOf(selectedBook.getId()));
            jLabel_BookName_.setText(selectedBook.getName());
            jLabel_BookName_.setVisible(true);
            Book_id_search = book_id;
            
            selectedMember = member.getMemberByID(member_id);
            jTextField_MemberID_.setText(String.valueOf(selectedMember.getId()));
            String fullname = selectedMember.getFirstName() + " " + selectedMember.getLastName();
            jLabel_MemberFullname_.setText(fullname);
            jLabel_MemberFullname_.setVisible(true);
            Member_id_search = member_id;
            
            String status = jTable_Issued_Books_.getValueAt(index, 2).toString();
            String issued_book = jTable_Issued_Books_.getValueAt(index, 3).toString();
            String return_book = jTable_Issued_Books_.getValueAt(index, 4).toString();
            String note = jTable_Issued_Books_.getValueAt(index, 5).toString();
            
            //display the date
            Date issDate = new SimpleDateFormat("yyyy-MM-dd").parse(issued_book);
            jDateChooser_IssueDate_.setDate(issDate);
            
            Date rtnDate = new SimpleDateFormat("yyyy-MM-dd").parse(return_book);
            jDateChooser_ReturnDate_.setDate(rtnDate);
            
            jTextArea_Note_.setText(note);
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_Issued_Books_MouseClicked

    private void jComboBox_Status_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Status_ActionPerformed
        // display data on jTable depending on the jCombobox selected value
        String status = jComboBox_Status_.getSelectedItem().toString();
        if(status.equalsIgnoreCase("all")) {
            status = "";
        }
        populateJtableWithIssuedBooks(status.toLowerCase());
    }//GEN-LAST:event_jComboBox_Status_ActionPerformed

    private void jButton_Return_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Return_MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Return_MouseEntered

    private void jButton_Delete_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Delete_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Delete_MouseClicked

    private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_ActionPerformed
        // delete the selected issue from database
        
        // get the selected row index
        int index = jTable_Issued_Books_.getSelectedRow();
        
        try {
            // get values
            int book_id = Integer.parseInt(jTable_Issued_Books_.getValueAt(index, 0).toString());
            int member_id = Integer.parseInt(jTable_Issued_Books_.getValueAt(index, 1).toString());
            String issued_date = jTable_Issued_Books_.getValueAt(index, 3).toString();

            issue_Book.removeFromIssuedTable(book_id, member_id, issued_date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select item from table to delete", "Notification", 2);
        }
    }//GEN-LAST:event_jButton_Delete_ActionPerformed

    // create a function to set border
    public void setBorderToJlabel(JLabel label, Color color) {
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, color);
        label.setBorder(border);
    }
    
    // create a function to populate the jtable with issued books
    public void populateJtableWithIssuedBooks(String status) {
        ArrayList<Issue_Book> issuedBooksList = issue_Book.issuedBookList(status);
        
        
        // jtable columns
        String[] colNames = {"Book","Member", "Status", "Iss-Date", "Rtn-Date", "Note"};
        
        // jtable rows
        Object[][] rows = new Object[issuedBooksList.size()][colNames.length];
        
        for(int i = 0; i < issuedBooksList.size(); i++) {
            rows[i][0] = issuedBooksList.get(i).getBook_id();
            rows[i][1] = issuedBooksList.get(i).getMember_id();
            rows[i][2] = issuedBooksList.get(i).getStatus();
            rows[i][3] = issuedBooksList.get(i).getIssue_date();
            rows[i][4] = issuedBooksList.get(i).getReturn_date();
            rows[i][5] = issuedBooksList.get(i).getNote();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Issued_Books_.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete_;
    private javax.swing.JButton jButton_Lost_;
    private javax.swing.JButton jButton_Return_;
    private javax.swing.JComboBox<String> jComboBox_Status_;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate_;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate_;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BookName_;
    private javax.swing.JLabel jLabel_CloseForm_;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_MemberFullname_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Issued_Books_;
    private javax.swing.JTextArea jTextArea_Note_;
    private javax.swing.JTextField jTextField_BookID_;
    private javax.swing.JTextField jTextField_MemberID_;
    // End of variables declaration//GEN-END:variables
}
